// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26qebPvsWXxHscoLW0MZI9U6IWJAafrc',
    appId: '1:836907422627:android:6688bbb2bdc2b2a5280016',
    messagingSenderId: '836907422627',
    projectId: 'finflow-3ae88',
    storageBucket: 'finflow-3ae88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAON3J-UjCqLP7w8kTrcB6k9DkNQZunNNA',
    appId: '1:836907422627:ios:09e6db8acfaebab9280016',
    messagingSenderId: '836907422627',
    projectId: 'finflow-3ae88',
    storageBucket: 'finflow-3ae88.firebasestorage.app',
    androidClientId: '836907422627-d1g0k7n7i9lubbe1pudh4bo82m58iv2f.apps.googleusercontent.com',
    iosClientId: '836907422627-dd6c2lb8itilhmb7qip9r9bmhnm13eof.apps.googleusercontent.com',
    iosBundleId: 'com.finflow.app',
  );
}
